update

diff --git a/.github/workflows/docker_builder_v2.yaml b/.github/workflows/docker_builder_v2.yaml
--- a/.github/workflows/docker_builder_v2.yaml
+++ b/.github/workflows/docker_builder_v2.yaml
@@ -37,6 +37,21 @@ jobs:
           else
             #set file to building
             jq --arg COMMIT_TO_TEST "$COMMIT_TO_TEST" '[.[] | if .hash == $COMMIT_TO_TEST then .build_status = "building" else . end]' docker_builder/builds.json >  $HOME/temp.json && mv  $HOME/temp.json docker_builder/builds.json
+            result=$(echo "$json" | jq --arg COMMIT_TO_TEST "$COMMIT_TO_TEST" 'if .type == "pull_request" and .hash == $COMMIT_TO_TEST then .label | split(":") as $pair | {owner: $pair[0], branch: $pair[1], hash: .hash} else empty end')
+
+            if [ "$result" != "null" ]; then
+              owner=$(echo "$result" | jq -r '.owner')
+              branch=$(echo "$result" | jq -r '.branch')
+              hash=$(echo "$result" | jq -r '.hash')
+
+              echo "owner=$owner" >> $GITHUB_OUTPUT
+              echo "branch=$branch" >> $GITHUB_OUTPUT
+            else
+              echo "owner=nanocurrency" >> $GITHUB_OUTPUT
+              echo "branch=develop" >> $GITHUB_OUTPUT
+            fi
+            
+            
             echo "continue=1" >> $GITHUB_OUTPUT
             echo "COMMIT_TO_TEST=$COMMIT_TO_TEST" >> $GITHUB_OUTPUT
 
@@ -50,29 +65,29 @@ jobs:
               git push origin testing/workflow_improve            
             fi            
           fi
-      # - name: checkout nanocurrency/nano-node
-      #   if: ${{ steps.compare_hash.outputs.continue > 0 }}
-      #   uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
-      #   with:
-      #     repository: nanocurrency/nano-node
-      #     submodules: "recursive"
-      #     ref: develop
-      #     path: nano-node
+      - name: checkout nanocurrency/nano-node
+        if: ${{ steps.compare_hash.outputs.continue > 0 }}
+        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
+        with:
+          repository: ${{ steps.compare_hash.outputs.owner }}/nano-node
+          submodules: "recursive"
+          ref:  ${{ steps.compare_hash.outputs.branch }}
+          path: nano-node
       - name: build docker image
         if: ${{ steps.compare_hash.outputs.continue > 0 }}
         id: docker_build
-        #working-directory: ./nano-node
+        working-directory: ./nano-node
         run: |
           DOCKER_TAG=${{ steps.compare_hash.outputs.COMMIT_TO_TEST }}
           BUILD_AT=$(date -u +%FT%TZ)          
-          #docker build -f docker/node/Dockerfile -t gr0v1ty/nano-node .
-          #if [ $? -ne 0 ]; then            
-            # Perform some action in case of failure
-            #echo "BUILD_STATUS='fail'" >> $GITHUB_OUTPUT
-          #else
+          docker build -f docker/node/Dockerfile -t gr0v1ty/nano-node .
+          if [ $? -ne 0 ]; then            
+            Perform some action in case of failure
+            echo "BUILD_STATUS='fail'" >> $GITHUB_OUTPUT
+          else
             echo "BUILD_STATUS='pass'" >> $GITHUB_OUTPUT            
             echo "DOCKER_TAG=gr0v1ty/nano-node:${DOCKER_TAG}" >> $GITHUB_OUTPUT  
-          #fi          
+          fi          
 
       #     # LOGIN to dockerhub
       #     # echo ${{ secrets.DH_PWD }} | docker login -u gr0v1ty --password-stdin
